### ISSUE TITLE
can not clone submodule

### ISSUE THREAD

**Issue by cldog** [RicherMans/PLDA#5]
HELLO RicherMans
when i clone your resp,i use 'git clone git@github.com:RicherMans/PLDA.git --recursive'
but it tell me these

Cloning into 'PLDA'...
remote: Enumerating objects: 723, done.
remote: Total 723 (delta 0), reused 0 (delta 0), pack-reused 723
Receiving objects: 100% (723/723), 151.66 KiB | 52.00 KiB/s, done.
Resolving deltas: 100% (447/447), done.
Checking connectivity... done.
fatal: no submodule mapping found in .gitmodules for path 'scoring/htkpython'

is the submodule exist at this time?or i do something wrong?

THANK YOU

**Comment by RicherMans** [comment]
Uhh why not just:
```bash
git clone https://github.com/RicherMans/PLDA
```
?

**Comment by cldog** [comment]
when i use
`git clone https://github.com/RicherMans/PLDA`

the result is 

![2018-10-23 11 51 09](https://user-images.githubusercontent.com/24385283/47334651-3702ed80-d6ba-11e8-837a-bcfbffb54d13.png)

just as the photo, the htkpython folder is empty, and i want to clone the submodule htkpython

![2018-10-23 11 55 29](https://user-images.githubusercontent.com/24385283/47334764-995bee00-d6ba-11e8-8006-d460a5c28a59.png)

how can i clone the htkpython folder?

**Comment by RicherMans** [comment]
Whoops was my mistake, I accidentally added that module back in the day by adding a local git repository ( which is not available anymore )

**Comment by cldog** [comment]
i see,
is there something that can replace the lost module?
to continue my project,could you give me some suggestion?
THANK YOU

**Comment by RicherMans** [comment]
Oh that was just a module to read and write htk features ( Wrote that in C ). There are some alternatives online available:
[here](https://pypi.org/project/htk_io/)
and
[here](https://github.com/danijel3/PyHTK)

**Comment by cldog** [comment]
o98k,thanks again
