### ISSUE TITLE
Using kaldi plda model

### ISSUE THREAD

**Issue by lalimili6** [RicherMans/PLDA#8]
Hi Dear
How can I use Kaldi plda model?
suppose I have a plda model and two lists of i(x)-vectors in python, how can compute the distance between two vectors?

e.g.
I download Kaldi x-vector moel https://kaldi-asr.org/models/7/0007_voxceleb_v1_1a.tar.gz
and extract x-vectors of two voices and have two lists of numbers (or NumPy arrays) in python e.g. 
enrol = [1,1,1,1]
eval =   [2,2,2,2]
how can compute plda between two lists like above with the plda model?

thanks

**Comment by RicherMans** [comment]
Read the manual?
I wrote this project 5 years ago and can't remember any too wild specific details.
