### ISSUE TITLE
Could not find Atlas

### ISSUE THREAD

**Issue by zengxinch** [RicherMans/PLDA#9]
I install KALDI  (using ./configure --shared) and export KALDI.  There is a question about export ATLAS_DIR, I find that kaldi only install ATLAS HEADER, so the ATLAS_DIR directory is what? 
I tried to let ATLAS_DIR = KALDI_root or KALDI/tools/ATLAS_headers, but both of them failed.
![{PMPB0A4S1P)3Y7U I2LNGR](https://user-images.githubusercontent.com/38159923/126452637-04b18980-6b43-45b4-9043-2186c862d596.png)

**Comment by RicherMans** [comment]
Sorry but thats a KALDI issue. 
ATLAS is a BLAS library that you need in order to install Kaldi.

If you have root, just follow the [here](http://math-atlas.sourceforge.net/).
Otherwise, I think even conda supports a atlas installation.

In short: not related to the repo.

**Comment by zengxinch** [comment]
Thank you for your answer.
I have another two new question now.
1. The first way is to download the lib in here, and then install Kaldi, in this way, do I need to export ATLAS? if yes, the directory is the directory that blas library exists.
 2. Using conda means letting kaldi compiler be conda python?

**Comment by RicherMans** [comment]
1. My lib requires kaldi, so first kaldi then everything else.
2. using conda just means that you don't need to have root on your machine to install ATLAS or other BLAS libraries, but makes compilation somewhat more complicated.
